### PR TITLE
Add description and keywords meta tags for seo

### PR DESCRIPTION
**Pull request by Bengt**
Currently, Google does not list our website at all when searching for "Extinction Rebellion Oldenburg". This should give search engines the hint that we mean "Extinction Rebellion" by "XR".

### CODE REVIEW

**Comment by Bengt** [comment]
Yes, I can merge this on my own, but since this is my first contribution please review @leon3103.

**Comment by Bengt** [comment]
A better solution would be to write a short text stating who we are and what we do. However, this should be a quick fix that already increases visibility by a lot.

**Comment by leon3103** [comment]
Good Idea. Did not think about it yet. will merge it now.

**Comment by Bengt** [comment]
Cool, thanks!

**Pull request merged**
